export const PROMPTS: string[] = [
  "A dragon learning to ride a bicycle",
  "A robot trying to bake cookies",
  "A cat who thinks it's a superhero",
  "A haunted vending machine",
  "A giraffe in a tiny car",
  "A penguin at a beach party",
  "A wizard stuck in traffic",
  "A shark wearing pajamas",
  "An alien confused by a toaster",
  "A dinosaur taking a selfie",
  "A pirate at a job interview",
  "A moose doing ballet",
  "A clown at a quiet library",
  "A cactus that wants a hug",
  "A vampire who hates the night",
  "A snail winning a race",
  "A koala running a coffee shop",
  "A giant sandwich with feelings",
  "A cloud that forgot how to rain",
  "A squirrel planning a heist",
  "Eating spaghetti in a thunderstorm",
  "The worst superhero ever",
  "A squirrel discovering coffee",
  "Trying to fit a horse into a fridge",
  "A banana peel's revenge",
  "When the wifi goes down",
  "An octopus playing the drums",
  "A snowman in a sauna",
  "A time traveler from 1990",
  "A dog conducting an orchestra",
  "A ghost who is afraid of the dark",
  "The Mona Lisa with a mustache",
  "A unicorn stuck in traffic",
  "A ninja baking a cake",
  "A potato on a roller coaster",
  "A mermaid discovering shoes",
  "A zombie at a salad bar",
  "A pigeon stealing a diamond",
  "An angry piece of toast",
  "A bear trying to parallel park",
  "A sloth rushing to work",
  "A flamingo playing ice hockey",
  "A very confused chameleon",
  "A spider afraid of heights",
  "A cow jumping over a skyscraper",
  "A jellyfish wearing sunglasses",
  "A werewolf checking their phone",
  "A turtle doing a kickflip",
  "A beaver building a modern house",
  "A crab with a sword",
  "A worm escaping a bird",
  "A skunk selling perfume",
  "A banana riding a bicycle",
  "A pineapple going to school",
  "A cheeseburger playing a video game",
  "A cactus wearing mittens",
  "A toaster toasting bread on a camping trip",
  "A cloud having a pillow fight",
  "A pizza slice playing catch",
  "A piece of candy doing weightlifting",
  "A shark waterskiing",
  "A polar bear sipping lemonade",
  "A giraffe reading a bedtime story",
  "A dog skateboarding with a cool hat",
  "A cat driving a fire truck",
  "A walrus in a beach chair",
  "A pug on a treadmill",
  "A lizard putting on lipstick",
  "A mouse riding a motorcycle",
  "A crime scene where a donut lost its hole",
  "The moon fighting the sun over a sandwich",
  "A person with fruit for hair",
  "A basketball player dunking a chicken",
  "A cowgirl riding a polar bear",
  "A cereal box mascot moonwalking",
  "A fish swimming in a pool of Jello",
  "A monster sneezing out flowers",
  "A pencil sharpener eating a carrot",
  "An ice cream cone running from the sun",
  "A grumpy traffic cone",
  "A toilet paper roll in a superhero cape",
  "A teacup with legs",
  "A sleepy mailbox",
  "A hamburger taking a selfie",
  "A crying crayon",
  "A pair of scissors running a marathon",
  "A lightbulb having a bad hair day",
  "A confused doorknob",
  "A sneezing umbrella",
  "A robot knitting a sweater",
  "A dinosaur doing yoga",
  "A sassy lamp dancing",
  "A marshmallow roasting itself",
  "A taco with a mustache",
  "A battery feeling tired",
  "A remote control hiding under the sofa",
  "A key that forgot what it opens",
  "A mirror that shows the future",
  "A toothbrush fighting a cavity monster",
  "A balloon afraid of needles",
  "A compass that only points to pizza",
  "A dictionary that made up a new word",
  "A clock that decided to go backwards",
  "A magnet attracted to a wooden stick",
  "A telescope looking at itself",
  "A camera that only takes pictures of ghosts",
  "A violin that plays heavy metal",
  "A drum that wants to be a piano",
  "A paintbrush that only paints invisible things",
  "A map that leads to a pile of dirty socks",
  "A whistle that makes bubbles",
  "A hammer that thinks it's a screwdriver",
  "Dancing cactus",
  "Flying pizza",
  "Sad robot",
  "Sleepy dinosaur",
  "Angry broccoli",
  "Disco ball",
  "Space cat",
  "Ninja turtle",
  "Surfing penguin",
  "Rollerblading cow",
  "Singing potato",
  "Pirate ship",
  "Magic wand",
  "Haunted house",
  "Golden egg",
  "Giant mushroom",
  "Tiny elephant",
  "Rainbow bridge",
  "Electric guitar",
  "Popcorn rain",
  "Fire-breathing duck",
  "Boxing kangaroo",
  "Skateboarding frog",
  "Superhero hamster",
  "Underwater bicycle",
  "Invisible man",
  "Melting clock",
  "Talking tree",
  "Crying onion",
  "Laughing sun",
  "Chocolate mountain",
  "Bubble gum cloud",
  "Paper airplane",
  "Rocket boots",
  "Laser eyes",
  "Moon cheese",
  "Diamond ring",
  "Treasure chest",
  "Flying carpet",
  "Lava lamp",
  "Jellyfish disco",
  "Robot butler",
  "Vampire bat",
  "Zombie hand",
  "Mermaid tail",
  "Unicorn horn",
  "Dragon tail",
  "Phoenix wing",
  "Sphinx riddle",
  "Centaur race",
  "Minotaur maze",
  "Yeti sneeze",
  "Bigfoot selfie",
  "Loch Ness monster",
  "Alien handshake",
  "Cyberpunk city",
  "Haunted toaster",
  "Disco snail",
  "Pizza party",
  "Kung fu panda",
  "Space station",
  "Neon sign",
  "Crystal ball",
  "Flying car",
  "Jetpack dog",
  "Sushi boat",
  "Taco truck",
  "Hot dog stand",
  "Ice cream truck",
  "Ferris wheel",
  "Roller coaster",
  "Water slide",
  "Sand castle",
  "Lighthouse beacon",
  "Shipwreck gold",
  "Message in a bottle",
  "Jungle vine",
  "Desert oasis",
  "Arctic igloo",
  "Volcanic eruption",
  "Thunder cloud",
  "Shooting star",
  "Milky way",
  "Black hole",
  "Saturn rings",
  "Mars rover",
  "Robot dog",
  "Virtual reality",
  "Video game controller",
  "Headphones music",
  "Laptop computer",
  "Smart phone",
  "Smart watch",
  "Fitness tracker",
  "Drone flight",
  "Electric scooter",
  "Hoverboard ride",
  "Segway tour",
  "Unicycle balance",
  "Pogo stick",
  "Trampoline jump",
  "Parachute dive",
  "Hot air balloon",
  "Helicopter spin",
  "A submarine dive",
  "A giraffe with a short neck",
  "Eating salad with a chainsaw",
  "Cat playing piano with its tail",
  "Ghost trying to use a touch screen",
  "Polite superhero",
  "Dinosaur in a tuxedo at a disco",
  "Shark hiding in a bathtub",
  "Robot allergic to electricity",
  "Penguin flying a plane",
  "Wizard turned into a potato",
  "Octopus putting on a sweater",
  "Vegan vampire",
  "Zombie getting a manicure",
  "Skeleton rib xylophone",
  "Mermaid in a wheelchair",
  "Unicorn with a traffic cone horn",
  "Fire-breathing dragon afraid of fire",
  "Werewolf hairdresser",
  "Mummy using a vending machine",
  "Goblin motivational speaker",
  "Snail with a jetpack",
  "Pigeon wearing a tiny hat",
  "Cow moonlighting as a spy",
  "Hamster weightlifting a grape",
  "Beaver building a skyscraper",
  "Crab with a monocle",
  "Sloth on a sugar rush",
  "Flamingo doing the limbo",
  "Chameleon that forgot how to blend in",
  "Kangaroo in a bouncy house",
  "Koala as a disco king",
  "Walrus in a tutu",
  "Pug wearing a superhero cape",
  "Lizard playing a tiny violin",
  "Mouse riding a Roomba",
  "Donut that lost its hole",
  "Banana peel's revenge",
  "Snowman in a sauna",
  "Ghost afraid of the dark",
  "Mona Lisa with a mustache",
  "Ninja baking a cake",
  "Zombie at a salad bar",
  "Angry piece of toast",
  "Sloth rushing to work",
  "Spider afraid of heights",
  "Cow jumping over a skyscraper",
  "Werewolf checking their phone",
  "Turtle doing a kickflip",
  "Skunk selling perfume",
  "Pineapple going to school",
  "Cactus wearing mittens",
  "Pizza slice playing catch",
  "Shark waterskiing",
  "Giraffe reading a bedtime story",
  "Cat driving a fire truck",
  "Lizard putting on lipstick",
  "Grumpy traffic cone",
  "Teacup with legs",
  "Crying crayon",
  "Lightbulb with a bad hair day",
  "Marshmallow roasting itself",
  "Taco with a mustache",
  "Balloon afraid of needles",
  "Compass pointing only to pizza",
  "Clock going backwards",
  "Telescope looking at itself",
  "Violin playing heavy metal",
  "Whistle making bubbles",
  "Hammer thinking it's a screwdriver",
  "Electric scooter for squirrels",
  "Segway tour for sloths",
  "Unicycle balance for bears",
  "Pogo stick for penguins",
  "Trampoline jump for turtles",
  "Parachute dive for pigs",
  "Hot air balloon for hamsters",
  "Helicopter spin for hedgehogs"
];

export function pickPrompts(count: number, usedPrompts?: Set<string>): string[] {
  let pool = [...PROMPTS];
  if (usedPrompts) {
    pool = pool.filter(p => !usedPrompts.has(p));
  }
  
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  
  while (pool.length < count) pool.push(...PROMPTS);
  
  const picked = pool.slice(0, count);
  if (usedPrompts) {
    for (const p of picked) usedPrompts.add(p);
  }
  return picked;
}

