export const PROMPTS: string[] = [
  "A badger aggressively gardening",
  "A badger sculpting butter at a county fair",
  "A bag of chips containing 90 percent air",
  "A baguette being used in a fencing duel",
  "A baguette in a sword fight",
  "A baker dragon",
  "A baker wrestling with dough that has come alive",
  "A balloon afraid of needles",
  "A balloon terrified of a birthday party",
  "A banana peel's revenge",
  "A banana riding a bicycle",
  "A banana slipping on a human",
  "A bar of soap slipping away like a ninja",
  "A barber gorilla",
  "A barista creating latte art of a screaming potato",
  "A barista kangaroo",
  "A baseball batter hitting a flying saucer out of the park",
  "A basketball player dunking a chicken",
  "A bat wearing reading glasses upside down",
  "A battery feeling tired",
  "A bear playing poker",
  "A bear trying to assemble IKEA furniture",
  "A bear trying to parallel park",
  "A beaver building a modern house",
  "A beaver building a skyscraper out of toothpicks",
  "A billionaire hamster",
  "A black hole vacuuming up messy space junk",
  "A blender having a chaotic dance party",
  "A blueberry swelling up like a balloon",
  "A bodyguard protecting a pampered goldfish",
  "A book reading a human",
  "A bowl of cereal swimming with tiny marshmallow boats",
  "A bowl of ramen with noodles spelling SOS",
  "A bowler getting their fingers stuck in the bowling ball",
  "A bowling ball on strike",
  "A bowling ball wearing a shower cap",
  "A bowling pin sweating as the ball approaches",
  "A broccoli stalk pretending to be a giant redwood tree",
  "A broom dreaming of becoming a magic staff",
  "A bulldog wearing a frilly tutu",
  "A bumblebee delivering a tiny package like a courier",
  "A bunch of bananas sliding down a banister",
  "A burrito wrapped tighter than a mummy",
  "A bus driver giraffe",
  "A butcher playing the violin with sausages",
  "A butter knife feeling insecure around steak knives",
  "A cactus getting a haircut",
  "A cactus selling free hugs",
  "A cactus that wants a hug",
  "A cactus wearing mittens",
  "A calculator writing poetry about zero",
  "A camel carrying a swimming pool",
  "A camera that only takes pictures of ghosts",
  "A candy cane being used as a walking stick",
  "A capybara soaking in a hot tub with rubber ducks",
  "A carrot wearing stylish sunglasses in the dirt",
  "A cat driving a fire truck",
  "A cat judging you from across the room",
  "A cat trying to herd sheep",
  "A cat who thinks it's a superhero",
  "A cauldron bubbling over with strawberry milkshake",
  "A ceiling fan spinning out of control",
  "A centaur getting fitted for two pairs of pants",
  "A cereal box mascot moonwalking",
  "A chameleon failing an eye test",
  "A chameleon failing to blend into a disco ball",
  "A chandelier swinging like Tarzan",
  "A charging cable tied in twenty impossible knots",
  "A cheerful goblin",
  "A cheese wheel rolling downhill",
  "A cheeseburger playing a video game",
  "A chef bear",
  "A chef juggling hot frying pans filled with stir fry",
  "A chili pepper breathing literal fire",
  "A chimpanzee fixing a broken sports car",
  "A chinchilla taking a dust bath in powdered sugar",
  "A chocolate bar melting in somebody's pocket",
  "A clock running backwards to avoid Monday",
  "A clock that decided to go backwards",
  "A cloud dropping an anvil instead of rain",
  "A cloud having a pillow fight",
  "A cloud having an existential crisis",
  "A cloud raining cats and dogs literally",
  "A cloud that forgot how to rain",
  "A cloud trying to stay grounded",
  "A clown at a quiet library",
  "A clumsy acrobat",
  "A coach turtle",
  "A coconut falling on a pirate's treasure chest",
  "A coffee mug demanding decaf for once",
  "A compass that only points to pizza",
  "A competitive grandma",
  "A computer mouse chasing real cheese",
  "A computer using a mouse",
  "A confused alien",
  "A confused tourist ghost",
  "A construction worker building a giant pillow fort",
  "A cookie dipping itself in a glass of milk",
  "A couch cushion hiding loose change and TV remotes",
  "A cow jumping over a skyscraper",
  "A cowgirl riding a polar bear",
  "A crab with a sword",
  "A crime scene where a donut lost its hole",
  "A croissant pretending to be the crescent moon",
  "A crow solving a Rubik's cube",
  "A crying crayon",
  "A cucumber taking a luxury spa cucumber eye treatment",
  "A cupcake with a tower of frosting touching the ceiling",
  "A cyborg charging via solar panel while sunbathing",
  "A cyborg detective",
  "A cyclops trying to use 3D glasses at the cinema",
  "A deep sea diver arm-wrestling an octopus",
  "A dentist brushing the teeth of a smiling alligator",
  "A dentist shark",
  "A depressed snowman",
  "A detective interrogating a donut",
  "A detective investigating who stole the office donuts",
  "A dictionary that made up a new word",
  "A dinosaur doing yoga",
  "A dinosaur taking a selfie",
  "A dinosaur trying to use chopsticks",
  "A disco ball crying at a funeral",
  "A disco wizard",
  "A disco-loving mummy",
  "A dog conducting an orchestra",
  "A dog groomer giving a poodle a green mohawk",
  "A dog skateboarding with a cool hat",
  "A dog trying to catch its own tail on TV",
  "A dolphin surfing a giant tidal wave",
  "A donkey winning a chess tournament",
  "A donut crying because someone took its sprinkles",
  "A double cheeseburger smiling on webcam",
  "A dragon hoarding shiny disco balls in a cave",
  "A dragon learning to ride a bicycle",
  "A dramatic drama teacher",
  "A dramatic wizard",
  "A drone delivering a single slice of cheese",
  "A drum that wants to be a piano",
  "A duck in a business suit",
  "A dwarf measuring a beard with a golden ruler",
  "A fairy getting stuck on flypaper in a kitchen",
  "A fancy butler cat",
  "A fancy flamingo",
  "A farmer octopus",
  "A feather dusting a feather duster",
  "A ferret trapped in a giant tube of toothpaste",
  "A fire extinguisher catching on fire",
  "A fire hydrant spray-painting the street",
  "A firefighter rescuing a dragon stuck in a tall pine tree",
  "A fish out of water at a dance party",
  "A fish riding a bicycle underwater",
  "A fish swimming in a pool of Jello",
  "A flamingo playing ice hockey",
  "A flamingo practicing karate kicks",
  "A flashlight running out of batteries in a spooky cave",
  "A flight attendant demonstrating parachute origami",
  "A floating pair of pants",
  "A forgetful elephant",
  "A fork trying to eat soup unsuccessfully",
  "A fortune cookie with an insulting fortune",
  "A friendly ghost",
  "A frog waiting patiently for a kiss on a bench",
  "A frying pan flipping pancakes into ceiling fans",
  "A garden gnome escaping on a riding lawnmower",
  "A garlic clove warding off a tiny fruit fly",
  "A gecko selling car insurance door to door",
  "A genie misinterpreting a wish for a billion ducks",
  "A ghost haunting an empty room",
  "A ghost sheet caught in the laundry",
  "A ghost sweating in a hot sauna",
  "A ghost trying to scare a roomba",
  "A ghost trying to scare someone who has headphones on",
  "A ghost who is afraid of the dark",
  "A giant rubber duck taking over a city",
  "A giant sandwich with feelings",
  "A giant squid playing eight electric guitars",
  "A giraffe in a tiny car",
  "A giraffe reading a bedtime story",
  "A giraffe with a short neck",
  "A goat chewing on an expensive diploma",
  "A goblin arguing with customer service over a return",
  "A goldfish with a photographic memory",
  "A golfer accidentally putting into a gopher hole",
  "A gorilla having a dramatic soap opera moment",
  "A gossiping parrot",
  "A GPS giving sarcastic life advice",
  "A grape turning into a raisin under a tanning lamp",
  "A griffin delivering mail like a giant carrier pigeon",
  "A grumpy badger",
  "A grumpy cupcake refusing to be eaten",
  "A grumpy pirate",
  "A grumpy traffic cone",
  "A guinea pig dressed as a medieval king",
  "A gummy bear lifting heavy candy weights",
  "A gymnast getting stuck in a pretzel pose",
  "A hamster powering a rocket engine",
  "A haunted vending machine",
  "A hedgehog trying to pop bubble wrap",
  "A hesitant cloud learning to rain",
  "A hippo trying to squeeze into skinny jeans",
  "A hipster caveman",
  "A hipster ghost",
  "A hockey goalie defending with a giant waffle",
  "A hot dog running away from a bottle of relish",
  "A hotdog trying to blend in at a burger joint",
  "A hyperactive squirrel",
  "A jar of peanut butter that locked its own lid",
  "A jar of pickles holding a secret rave",
  "A jealous toaster watching an air fryer",
  "A jellyfish acting as a glowing bedside lamp",
  "A jellyfish learning to juggle",
  "A kaleidoscope showing a boring gray wall",
  "A kangaroo carrying groceries in its pouch",
  "A karaoke champion walrus",
  "A ketchup bottle farting loudly at dinner",
  "A key that forgot what it opens",
  "A knight fighting with a wet pool noodle",
  "A koala running a coffee shop",
  "A ladybug counting its own missing spots",
  "A landscaper trimming a hedge into a dinosaur shape",
  "A laser pointer playing with a giant lion",
  "A lazy mummy",
  "A lemon with an extremely sour facial expression",
  "A lemur leading an aerobics workout class",
  "A librarian shushing a thunderstorm outside",
  "A librarian t-rex",
  "A lifeguard polar bear",
  "A lightbulb having a bad hair day",
  "A lighthouse blinking Morse code gossip",
  "A lizard putting on lipstick",
  "A llama modeling on a Paris runway",
  "A lobster cracking open a safe with claws",
  "A lollipop getting stuck in somebody's beard",
  "A lost sock looking for its twin in Narnia",
  "A loud mime",
  "A magic carpet caught in high ceiling fans",
  "A magic wand shooting confetti instead of lightning",
  "A magnet attracted to a wooden stick",
  "A mail carrier being chased by an army of chihuahuas",
  "A manatee floating happily in space",
  "A map that leads to a pile of dirty socks",
  "A marathon runner getting distracted by a puppy",
  "A marshmallow getting golden brown by a campfire",
  "A marshmallow roasting itself",
  "A mascot having a dance-off against security",
  "A mechanic discovering squirrels living in an engine",
  "A mechanic hamster",
  "A medieval knight",
  "A medusa having a terrible snake hair day",
  "A meerkat on lookout with binoculars",
  "A mermaid discovering shoes",
  "A mermaid trapped in a giant fishbowl",
  "A mermaid trying on high heels underwater",
  "A meteorologist getting struck by indoor lightning",
  "A microwave counting down to nothing",
  "A minotaur getting lost in a corn maze",
  "A mirror that shows the future",
  "A mole digging into a secret bank vault",
  "A monster sneezing out flowers",
  "A moose doing ballet",
  "A moose on a trampoline",
  "A mosquito swatting a human with a tiny swatter",
  "A moth in love with a streetlamp",
  "A mountain climber reaching the summit and finding a hot dog stand",
  "A mouse riding a motorcycle",
  "A mummy getting unraveled by a playful cat",
  "A mushroom attending a business meeting",
  "A mushroom sheltering a miniature orchestra",
  "A mustard bottle spraying yellow water first",
  "A mysterious masterpiece",
  "A nervous astronaut",
  "A nervous skeleton",
  "A ninja baking a cake",
  "A paintbrush that only paints invisible things",
  "A painter accidentally painting themselves into a corner",
  "A painter sloth",
  "A pair of headphones tangled into a sculpture",
  "A pair of scissors running a marathon",
  "A pair of sunglasses feeling too cool for the beach",
  "A pancake stack leaning like the Tower of Pisa",
  "A panda refusing to eat anything except bamboo sushi",
  "A pegasus parallel parking in a cloud",
  "A pelican stuffing an entire watermelon in its pouch",
  "A pencil sharpener eating a carrot",
  "A pencil taking a hot bubble bath",
  "A penguin at a beach party",
  "A penguin building a sandcastle",
  "A person with fruit for hair",
  "A philosophical frog",
  "A phoenix catching a cold and sneezing embers",
  "A piece of candy doing weightlifting",
  "A pigeon reviewing a restaurant",
  "A pigeon stealing a diamond",
  "A piggy bank on a strict diet",
  "A pillow that is never on the cool side",
  "A pilot penguin",
  "A piñata seeking revenge on children",
  "A pineapple going to school",
  "A pineapple trying on sunglasses at the beach",
  "A piranha at a vegetarian buffet",
  "A pirate at a job interview",
  "A pirate returning a library book",
  "A pizza slice playing catch",
  "A pizza slice stretching cheese across the room",
  "A plant watering a human",
  "A plate of spaghetti resembling a messy yarn ball",
  "A plumber discovering a portal to another dimension in a drain",
  "A plumber mermaid",
  "A polar bear sipping lemonade",
  "A police officer giving a speeding ticket to a cheetah",
  "A polite goblin",
  "A popcorn kernel refusing to pop",
  "A porcupine receiving a very cautious hug",
  "A posh poodle",
  "A potato dreaming of becoming french fries",
  "A potato on a roller coaster",
  "A potato winning a beauty contest",
  "A praying mantis practicing kung fu on a dandelion",
  "A princess rescuing a prince who is playing video games",
  "A printer displaying 'PC LOAD LETTER' out of spite",
  "A pufferfish inflating after being told a spooky secret",
  "A pug on a treadmill",
  "A pumpkin carving a human face for Halloween",
  "A quarterback throwing a hot dog for a touchdown",
  "A raccoon hacking a vending machine",
  "A race car driver stopping at a red light during a race",
  "A referee blowing a kazoo instead of a whistle",
  "A remote control hiding under the sofa",
  "A retired superhero",
  "A rhino carefully painting a delicate porcelain teacup",
  "A robot experiencing love for the first time",
  "A robot knitting a sweater",
  "A robot shedding a single oily tear",
  "A robot trying to bake cookies",
  "A robot trying to understand why humans cry",
  "A robot with a heart of gold",
  "A rock climber discovering a vending machine halfway up",
  "A rooster waking up too late and panicking",
  "A rover finding a squeaky dog toy on Mars",
  "A royal pug",
  "A rubber duck captaining a bathtub armada",
  "A runaway robot",
  "A salt shaker gossiping with a pepper grinder",
  "A sandwich eating a human",
  "A sandwich with twenty layers of bacon",
  "A sassy lamp dancing",
  "A sassy seagull",
  "A satellite taking blurry paparazzi photos of the moon",
  "A scuba diver finding a submerged tea party",
  "A sea lion playing trumpet in a jazz band",
  "A seagull executing an airborne fry heist",
  "A seagull stealing an entire slice of pizza",
  "A seahorse winning an underwater steeplechase",
  "A secret agent cat",
  "A secret agent wearing a disguise made of cardboard",
  "A selfie stick that achieved consciousness",
  "A selfie-obsessed yeti",
  "A sentient refrigerator judging your late night snack",
  "A shark waterskiing",
  "A shark wearing pajamas",
  "A ship captain steering through a sea of lemonade",
  "A singing detective auditioning for a Broadway musical",
  "A singing detective entering a hot dog eating contest by accident",
  "A singing detective failing a driver's license road test miserably",
  "A singing detective giving a TED talk about string cheese",
  "A singing detective ordering a complicated drink at a trendy café",
  "A singing detective stepping on a Lego brick while barefoot",
  "A singing detective struggling to open a stubborn pickle jar",
  "A singing detective trying to fold a fitted sheet in zero gravity",
  "A skateboarder doing an ollie over a sleeping bear",
  "A skateboarding penguin",
  "A skeleton dancing the Macarena",
  "A skeleton drinking milk",
  "A skunk giving a luxury aromatherapy massage",
  "A skunk selling perfume",
  "A sky diver eating a sandwich during freefall",
  "A sleepy koala",
  "A slice of pizza riding a skateboard",
  "A sloth participating in a rap battle",
  "A sloth rushing to work",
  "A sloth winning an Olympic sprint",
  "A slug leaving a trail of glitter wherever it goes",
  "A smart speaker listening to alien radio signals",
  "A smart thermostat fighting an electric heater",
  "A smartphone with 1% battery screaming for help",
  "A snail competing in Formula 1",
  "A snail on a rocket",
  "A snail winning a race",
  "A snail zooming past on rollerblades",
  "A sneaky raccoon",
  "A sneezing umbrella",
  "A snowglobe with a desert inside",
  "A snowman buying a heater",
  "A snowman holding an umbrella",
  "A snowman melting under a tanning bed",
  "A space marine gardening delicate purple roses",
  "A spacesuit filled with hundreds of helium balloons",
  "A spider afraid of heights",
  "A spider weaving a colorful hammock",
  "A spoon pretending to be a catapult",
  "A spy hiding inside a hollowed-out wedding cake",
  "A squirrel discovering coffee",
  "A squirrel hiding a giant nut",
  "A squirrel planning a heist",
  "A squirrel trapped inside a snowglobe",
  "A stingray gliding across an ice skating rink",
  "A strawberry covered in freckles",
  "A stressed-out barista",
  "A stubborn shopping cart with one broken wheel",
  "A submarine dive",
  "A submarine stuck in a bathtub",
  "A sumo wrestler balancing on a tightrope",
  "A superhero dog",
  "A superhero stuck in a revolving door",
  "A superhero whose only power is making toast",
  "A surfer riding a wave on an ironing board",
  "A surgeon playing Operation before real surgery",
  "A sushi roll practicing synchronized swimming",
  "A suspicious flamingo",
  "A T-Rex trying to make a bed",
  "A taco falling apart on the very first bite",
  "A taco with a mustache",
  "A taxi driver picking up a family of penguins",
  "A teacup with legs",
  "A teapot whistling an opera aria",
  "A telescope looking at itself",
  "A telescope looking back at an astronomer",
  "A tennis player serving a watermelon over the net",
  "A thunderstorm trapped inside a mason jar",
  "A time traveler",
  "A time traveler from 1990",
  "A time traveler trying to pay with cryptocurrency in 1850",
  "A tiny Chihuahua with big dreams",
  "A toad wearing a tiny velvet crown",
  "A toaster scared of bread",
  "A toaster that shoots toast through the roof",
  "A toaster that shoots waffles",
  "A toaster toasting bread on a camping trip",
  "A toilet paper roll in a superhero cape",
  "A tomato insisting it is technically a fruit",
  "A toothbrush fighting a cavity monster",
  "A tortoise zooming down a hill on a skateboard",
  "A toucan presenting a TV weather forecast",
  "A traffic light having an identity crisis",
  "A train conductor stopping for a turtle crossing the tracks",
  "A tree climbing a squirrel",
  "A tree with an attitude",
  "A troll demanding tolls in chocolate bars under a bridge",
  "A tuba blowing soapy bubbles",
  "A tube of toothpaste giving its last squeeze",
  "A turtle doing a kickflip",
  "A turtle in a marathon",
  "A UFO tractor beam lifting an angry cat",
  "A unicorn parallel parking a tractor",
  "A USB drive plugged in the wrong way three times",
  "A vacuum cleaner getting revenge on dust bunnies",
  "A vampire checking for grey hairs",
  "A vampire checking his reflection in a smartphone camera",
  "A vampire checking themselves in a mirror",
  "A vampire who hates the night",
  "A vampire with a sunburn",
  "A vending machine rejecting a crisp dollar bill",
  "A very confused chameleon",
  "A very loud ninja",
  "A veterinarian giving a checkup to a grumpy hedgehog",
  "A violin that plays heavy metal",
  "A waffle iron making superhero logos on waffles",
  "A waiter carrying a thirty-plate tower of pancakes",
  "A walrus in a beach chair",
  "A walrus stuck in a hammock",
  "A watermelon competing in a cannonball contest",
  "A webcam catching a cat plotting world domination",
  "A weeping onion cutting a chef",
  "A weightlifter struggling to lift an empty barbell",
  "A werewolf checking their phone",
  "A werewolf shedding all over a velvet sofa",
  "A whistle that makes bubbles",
  "A Wi-Fi router on strike for better working conditions",
  "A window washer drawing smiley faces on skyscrapers",
  "A wise owl",
  "A witch parallel parking her broomstick in a tight spot",
  "A wizard microwaving a magic potion",
  "A wizard stuck in traffic",
  "A wizard summoning pizza instead of a fireball",
  "A wizard who lost his wand",
  "A worm driving an apple car",
  "A worm escaping a bird",
  "A wristwatch running five minutes fast intentionally",
  "A zebra trying to remove its own stripes",
  "A zombie applying sunscreen at a beach resort",
  "A zombie at a salad bar",
  "Air traffic controller guiding Santa's sleigh",
  "Alarm clock getting smashed",
  "Alarm clock running away on tiny wheels",
  "Alien cooking dinner with a microwave",
  "Alien cooking pancakes",
  "Alien dancing at a disco",
  "Alien dancing in the rain",
  "Alien drinking coffee",
  "Alien drinking from a giant cup",
  "Alien exploring a castle",
  "Alien exploring an underwater city",
  "Alien getting chased by a goose",
  "Alien getting lost inside a shopping mall",
  "Alien handshake",
  "Alien learning how to cook pancakes",
  "Alien ordering a hamburger",
  "Alien playing basketball",
  "Alien playing tennis with a robot",
  "Alien riding a camel through the desert",
  "Alien searching for a lost shoe",
  "Alien searching for the perfect sandwich",
  "Alien taking a bath",
  "Alien taking a bath in a tiny tub",
  "Alien taking a dog for a walk",
  "Alien taking a photograph of Earth",
  "Alien taking a train through the mountains",
  "Alien tourist losing luggage in Roswell",
  "Alien tourist taking photos",
  "Alien trying to catch a butterfly",
  "Alien trying to cook spaghetti",
  "Alien trying to open a locked door",
  "Alien trying to play the piano",
  "Alien trying to understand a birthday cake",
  "Alien trying to use a vending machine",
  "Alien visiting a medieval castle",
  "Alien visiting the beach",
  "Alpaca in a turtleneck",
  "An accountant yeti",
  "An airline pilot asking for road directions out the window",
  "An alarm clock getting hit with a sledgehammer",
  "An alien confused by a toaster",
  "An alien tourist taking selfies at Stonehenge",
  "An alien trying ice cream for the first time",
  "An alien trying on a hat",
  "An alpaca at a fancy hair salon",
  "An anchor floating like a feather",
  "An angry cloud shooting lasers",
  "An angry piece of toast",
  "An ant lifting a bowling ball with one hand",
  "An apple falling on an unsuspecting scientist",
  "An armadillo bowling a perfect strike",
  "An asteroid wearing a party hat as it zooms past Earth",
  "An astronaut losing their car keys in deep space",
  "An astronaut stepping on a lego piece",
  "An astronaut trying to eat soup in zero gravity",
  "An avocado decaying in fast forward",
  "An avocado that went from rock hard to rotten in 5 seconds",
  "An awkward teenager alien",
  "An eager beaver",
  "An electrician tangled in twenty colorful wires",
  "An elephant hiding behind a skinny lamp post",
  "An elf getting tangled in Christmas tree tinsel",
  "An ice cream cone running from the sun",
  "An ice cream sundae wearing an avalanche beacon",
  "An ice cube melting dramatically in a drink",
  "An iguana sunbathing on an active volcano",
  "An octopus playing the drums",
  "An octopus untangling headphones",
  "An onion crying at its own sad movie",
  "An orange peeling off its jacket in the heat",
  "An orc crying while watching a romantic comedy",
  "An otter juggling precious pearls",
  "An overenthusiastic gym bro",
  "An owl wearing night vision goggles",
  "An umbrella turning completely inside out in the rain",
  "An undercover ninja",
  "Angry broccoli",
  "Angry goose chasing someone",
  "Angry storm cloud",
  "Archaeologist digging up yesterday's leftovers",
  "Archer shooting a bullseye on a spinning dartboard",
  "Arctic igloo",
  "Armadillo curler sliding across the ice",
  "Armadillo rolling through a bowling alley",
  "Artist painting a potato",
  "Astronaut bowling with planets",
  "Astronaut playing guitar on the moon",
  "Astronaut repairing a satellite",
  "Astronaut watering plants on Mars",
  "ATM spitting out Monopoly money",
  "Avocado going brown in two seconds",
  "Baby controlling a spaceship",
  "Bagel balancing on a coffee cup rim",
  "Banana peeling itself in the summer heat",
  "Banana sliding down a rainbow",
  "Barcode scanner bleeping a funny melody",
  "Bat reading upside down",
  "Bear cooking dinner for its friends",
  "Bear eating with a fork",
  "Beaver building a skyscraper",
  "Beaver gnawing a giant wooden spoon",
  "Beaver sculpting a wooden marble statue",
  "Bicycle pedaling itself down the street",
  "Bigfoot posing for a photo",
  "Bigfoot selfie",
  "Black hole",
  "Blacksmith forging a golden butter knife",
  "Boba pearl hiding at the bottom of the straw",
  "Boombox serenading a microwave",
  "Boomerang refusing to come back",
  "Boxer punching a soft fluffy pillow",
  "Brain doing pushups on a yoga mat",
  "Brave toaster on a rescue mission",
  "Broom sweeping itself under the rug",
  "Bubble gum cloud",
  "Buff potato lifting weights",
  "Building a house on top of a cloud",
  "Building a rocket out of cardboard",
  "Building a sandcastle underwater",
  "Building a snow fort in summer",
  "Building a snowman in the desert",
  "Building a treehouse during a hurricane",
  "Building furniture without reading the instructions",
  "Bumblebee delivering a tiny pizza",
  "Cactus drinking through a straw",
  "Cactus getting fitted for a sweater",
  "Camera flash blinding a ghost",
  "Campfire roasting tiny marshmallows on sticks",
  "Camping inside a supermarket",
  "Candle blowing out its own flame",
  "Cape caught in a door",
  "Capybara meditating under a waterfall of boba",
  "Cat attending a rock concert",
  "Cat chasing a butterfly",
  "Cat chasing a mouse through a castle",
  "Cat climbing a curtain",
  "Cat discovering a secret passage",
  "Cat driving a taxi",
  "Cat exploring a haunted castle",
  "Cat exploring a secret laboratory",
  "Cat fishing from a pirate ship",
  "Cat guarding a sleeping baby",
  "Cat guarding a treasure chest",
  "Cat hiding from a dragon",
  "Cat hiding from a vacuum cleaner",
  "Cat hiding inside a box",
  "Cat in a cardboard box",
  "Cat playing chess",
  "Cat playing drums at a concert",
  "Cat playing piano with its tail",
  "Cat playing with a ball of yarn",
  "Cat riding a hot-air balloon",
  "Cat running a lemonade stand",
  "Cat sleeping on a pile of books",
  "Cat stealing a fish from a pirate",
  "Cat stealing a magician's wand",
  "Cat stealing a sandwich",
  "Cat trying to catch a laser pointer",
  "Cat trying to fly with homemade wings",
  "Cat trying to open a jar",
  "Cat trying to wake up its sleeping owner",
  "Cat watching a movie",
  "Cat watching a thunderstorm",
  "Cat watching birds through a window",
  "Cat wearing a superhero cape",
  "Catapult launching a wedding cake",
  "Cello playing itself in an empty theater",
  "Centaur race",
  "Centaur struggling to buy matching pants",
  "Centaur trying to ride a tandem bicycle",
  "Chalk drawing coming alive in the rain",
  "Chameleon blending into a Hawaiian shirt",
  "Chameleon hiding as wallpaper",
  "Chasing a chicken through an airport",
  "Chasing a runaway shopping cart",
  "Chef baking a cake for a monster",
  "Chef baking an enormous cake",
  "Chef baking cookies",
  "Chef balancing plates on a unicycle",
  "Chef catching a falling cake",
  "Chef chasing a chicken out of the kitchen",
  "Chef chasing a giant tomato",
  "Chef cooking breakfast for a giant",
  "Chef cooking for a group of penguins",
  "Chef cooking for a hundred hungry monsters",
  "Chef cooking inside a spaceship",
  "Chef cooking on a campfire",
  "Chef cooking soup for a dragon",
  "Chef escaping from a kitchen full of chickens",
  "Chef fighting with a giant lobster",
  "Chef flipping burgers",
  "Chef juggling cooking utensils",
  "Chef juggling giant vegetables",
  "Chef juggling pizzas",
  "Chef preparing a feast",
  "Chef preparing food for a royal banquet",
  "Chef riding a skateboard through the kitchen",
  "Chef running a restaurant for dragons",
  "Chef serving dinner to a giant",
  "Chef serving ice cream to penguins",
  "Chef serving spaghetti to pirates",
  "Chef throwing a birthday party",
  "Chef throwing a surprise party for a potato",
  "Chef throwing vegetables into a frying pan",
  "Chef trying to rescue a burning cake",
  "Chef trying to serve dinner during an earthquake",
  "Chef with a pancake on head",
  "Chinchilla crowned king of the fluff",
  "Chocolate mountain",
  "Climbing a mountain made of ice cream",
  "Climbing out of a birthday cake",
  "Clown driving a limousine",
  "Compass spinning dizzy circles",
  "Conductor leading barking dogs",
  "Construction crane eating pink cotton candy",
  "Cow moonlighting as a spy",
  "Crab building a sandcastle with tiny buckets",
  "Crab DJ at the beach",
  "Crab with a monocle",
  "Crocodile brushing teeth",
  "Crying onion",
  "Crystal ball",
  "Crystal ball showing yesterday's lottery numbers",
  "Cupcake with a leaning tower of frosting",
  "Cupid with broken arrows",
  "Curler scrubbing the ice with a toothbrush",
  "Cyberpunk city",
  "Cyclops getting an eye exam",
  "Dancing cactus",
  "Dancing during a job interview",
  "Dancing neon snail on rollerblades",
  "Deep sea welder fixing a leaky submarine",
  "Dentist cleaning Dracula's fangs",
  "Dentist inspecting an alligator's smile",
  "Desert oasis",
  "Detective dusting a donut for fingerprints",
  "Detective following suspicious footprints",
  "Detective searching for cookies",
  "Diamond ring",
  "Dinosaur DJ at a party",
  "Dinosaur in a tuxedo at a disco",
  "Disco ball",
  "Discovering that the moon is made of cheese",
  "Diver doing a belly flop into a puddle",
  "Doctor examining a very nervous robot",
  "Dog becoming a detective",
  "Dog becoming mayor of a small town",
  "Dog becoming the captain of a ship",
  "Dog carrying a giant bone",
  "Dog chasing a flying frisbee",
  "Dog chasing a mail carrier on a bicycle",
  "Dog chasing a rabbit",
  "Dog chasing a rabbit through the snow",
  "Dog chasing a runaway balloon",
  "Dog delivering a package",
  "Dog digging a tunnel",
  "Dog digging a very deep hole",
  "Dog digging for treasure",
  "Dog discovering a hidden cave",
  "Dog escaping from a bathtub",
  "Dog finding a buried chest",
  "Dog flying a kite",
  "Dog playing chess against a cat",
  "Dog playing drums",
  "Dog playing the saxophone",
  "Dog riding a dinosaur",
  "Dog riding a skateboard down a hill",
  "Dog surfing on a pizza",
  "Dog swimming across a river",
  "Dog swimming with a shark",
  "Dog trying to catch a frisbee on the moon",
  "Dog wearing a crown",
  "Dog wearing a pirate costume",
  "Donut doing hula hoop",
  "Dragon blowing smoke rings",
  "Dragon cooking soup",
  "Dragon drinking boba tea",
  "Dragon flying above a city",
  "Dragon flying through the clouds",
  "Dragon guarding a birthday cake",
  "Dragon learning how to skateboard",
  "Dragon playing hide-and-seek",
  "Dragon playing with a rubber duck",
  "Dragon protecting a treasure",
  "Dragon reading a book",
  "Dragon shopping for groceries",
  "Dragon sitting beside a campfire",
  "Dragon sitting on a mountain",
  "Dragon sleeping in a cave",
  "Dragon tail",
  "Dragon taking a selfie with a tourist",
  "Dragon trying to blow out a volcano",
  "Dragon trying to fit through a tiny doorway",
  "Dragon trying to read a newspaper",
  "Dragon with a sore throat blowing smoke rings",
  "Dragon working as a taxi driver",
  "Drone flight",
  "Dropping a phone on your face in bed",
  "Duck in yellow rainboots",
  "Eating a powdered donut without licking lips",
  "Eating salad with a chainsaw",
  "Electric guitar",
  "Escaping from a collapsing sandcastle",
  "Escaping from an angry goose",
  "Exploring a completely empty amusement park",
  "Eye of the storm wearing giant sunglasses",
  "Fairy trapped inside a light bulb",
  "Farmer driving a tractor through a supermarket",
  "Farmer milking a very confused cow",
  "Fencer poking a juice box",
  "Ferret stealing a diamond tiara",
  "Ferris wheel",
  "Finding a monster under the bed",
  "Finding a penguin inside the refrigerator",
  "Finding a secret passage behind the bookshelf",
  "Finding a treasure chest in a swimming pool",
  "Finding treasure beneath the sofa",
  "Fire-breathing dragon afraid of fire",
  "Fire-breathing duck",
  "Firefighter rescuing a tiny rubber duck",
  "Firefighter stuck in a tree",
  "Fish watching television",
  "Fitness tracker",
  "Flamingo balancing on a high wire",
  "Flamingo doing the limbo",
  "Flamingo on ice skates",
  "Flamingo standing on a paddleboard",
  "Flying a kite during a thunderstorm",
  "Flying carpet",
  "Flying pizza",
  "Folding a fitted sheet into an origami crane",
  "Frankenstein's monster frightened by a kitten",
  "French fry fencing with a toothpick",
  "Frog turning into a confused accountant",
  "Garden gnome riding a runaway skateboard",
  "Gargoyle doing morning yoga on a cathedral",
  "Generating 1000+ distinct prompts...",
  "Genie granting a wish for 10,000 marshmallows",
  "Getting chased by a giant cupcake",
  "Getting your sleeve caught on a door handle",
  "Ghost floating through the wrong wall",
  "Ghost taking a family vacation photo",
  "Ghost trying to order a sandwich",
  "Ghost trying to use a touch screen",
  "Ghost wearing a backward sheet",
  "Giant mushroom",
  "Giraffe stuck in a doorway",
  "Giraffe trying to limbo under a broomstick",
  "Goat eating a tin can",
  "Goblin demanding toll payment in shiny pennies",
  "Goblin motivational speaker",
  "Golden egg",
  "Goldfish dreaming of sharks",
  "Goldfish escaping via a water gun",
  "Golfer landing a ball inside a pelican's mouth",
  "Gorilla inspecting a tiny ladybug",
  "Gorilla knitting a warm wool scarf",
  "Gorilla solving a Rubik's cube with feet",
  "GPS arguing with the radio",
  "Grandfather clock doing karate",
  "Grandma chasing a dragon",
  "Grandma climbing a giant staircase",
  "Grandma competing in a wrestling match",
  "Grandma driving a race car",
  "Grandma flying a helicopter",
  "Grandma flying through outer space",
  "Grandma playing guitar",
  "Grandma teaching a monster how to knit",
  "Grandpa building a rocket",
  "Grandpa escaping from a haunted house",
  "Grandpa fishing from a boat",
  "Grandpa learning breakdancing",
  "Grandpa making a snowman",
  "Grandpa repairing a spaceship",
  "Grandpa riding a mechanical bull",
  "Grandpa trying to catch a fish with his hands",
  "Grandpa trying to lift a giant pumpkin",
  "Gummy bear climbing Mount Everest",
  "Gymnast stuck in an awkward pretzel pose",
  "Hamster piloting a miniature cardboard plane",
  "Hamster pirate captain",
  "Hamster weightlifting a grape",
  "Harmonica played by an enthusiastic gust of wind",
  "Haunted house",
  "Headphones having a tangled wrestling match",
  "Headphones music",
  "Heart wearing boxing gloves in an arena",
  "Helicopter spin",
  "High jumper landing in a bowl of pudding",
  "Hippopotamus tip-toeing across eggshells",
  "Hockey goalie blocking pucks with a trash can lid",
  "Hot air balloon",
  "Hot dog stand",
  "Hourglass dripping with strawberry syrup",
  "Hourglass running out of jelly beans",
  "Hoverboard ride",
  "Hovering grocery cart with jet boosters",
  "Hyperactive espresso cup",
  "Ice cream truck",
  "Invisible man",
  "Jellyfish disco",
  "Jetpack dog",
  "Jetpack powered by sparkling water",
  "Jungle vine",
  "Kangaroo delivering mail across the outback",
  "Kangaroo in a bouncy house",
  "King with a burger crown",
  "Kite pulling a small child into the sky",
  "Knight chasing a runaway horse",
  "Knight climbing a castle tower",
  "Knight eating at a restaurant",
  "Knight eating dinner with a dragon",
  "Knight eating spaghetti",
  "Knight fighting a giant octopus",
  "Knight fighting a rubber chicken",
  "Knight opening a mysterious chest",
  "Knight ordering food at a drive-through",
  "Knight ordering pizza",
  "Knight polishing a dragon's armor",
  "Knight rescuing a cat from a tree",
  "Knight riding a scooter into battle",
  "Knight riding through a forest",
  "Knight trying to climb a castle wall",
  "Knight trying to defeat a giant crab",
  "Knight trying to rescue a princess from a vending machine",
  "Koala arm wrestling",
  "Koala as a disco king",
  "Koala competing in a thumb war",
  "Koala hugging a giant chocolate bar",
  "Kung fu panda",
  "Laptop computer",
  "Laser eyes",
  "Laughing sun",
  "Lava lamp",
  "Lava lamp giving life advice",
  "Lawnmower shaving a giant peach",
  "Lemon puckering from its own sour juice",
  "Leprechaun with a pot of pennies",
  "Leprechaun's gold pot full of chocolate coins",
  "Lighthouse beacon",
  "Lightning bolt caught inside a lightbulb",
  "Lizard playing a tiny violin",
  "Llama chewing through electric cables",
  "Llama drinking a smoothie",
  "Lobster DJ spinning vinyl records",
  "Lobster giving a handshake",
  "Loch Ness monster",
  "Loch Ness monster asking for directions",
  "Lumberjack hugging a giant redwood",
  "Lumberjack petting a flower",
  "Magic carpet tangled in ceiling fan blades",
  "Magic wand",
  "Magician pulling a watermelon from a top hat",
  "Marathon runner chased by a baby duckling",
  "Mars rover",
  "Marshmallow sunbathing over a matchstick",
  "Mechanic finding a raccoon inside an engine",
  "Meditating sushi roll",
  "Medusa getting a blowout at a salon",
  "Medusa's hair having an argument",
  "Meerkat standing on top of a traffic cone",
  "Melting clock",
  "Mermaid in a fish tank",
  "Mermaid tail",
  "Message in a bottle",
  "Milky way",
  "Mime in an invisible box",
  "Mirror arguing with its reflection",
  "Mirror reflecting three seconds into the past",
  "Mole wearing subterranean goggles",
  "Money growing on a potted ficus tree",
  "Monkey solving a puzzle",
  "Monster attending a yoga class",
  "Monster brushing its teeth",
  "Monster cooking dinner",
  "Monster dancing at a wedding",
  "Monster eating a giant hamburger",
  "Monster eating birthday cake",
  "Monster eating spaghetti at a fancy restaurant",
  "Monster getting scared by a balloon",
  "Monster hiding from a tiny kitten",
  "Monster hiding under a bed",
  "Monster learning to cook",
  "Monster ordering coffee",
  "Monster ordering food at a restaurant",
  "Monster playing the violin",
  "Monster riding a bicycle downhill",
  "Monster scared of a mouse",
  "Monster taking a family portrait",
  "Monster trying to catch a chicken",
  "Monster trying to open a refrigerator",
  "Monster trying to ride a skateboard",
  "Monster working behind a supermarket checkout",
  "Moon cheese",
  "Moon wearing a nightcap and snoring",
  "Mosquito lifting tiny dumbbells",
  "Mummy tangled in colorful party streamers",
  "Mummy unraveling on an escalator",
  "Mummy untangling bandages",
  "Neon sign",
  "Nessie asking for spare change",
  "Ninja stepping on a squeaky toy",
  "Ninja turtle",
  "Ocean wave freezing into solid glass",
  "Octopus juggling ice cream",
  "Octopus putting on a sweater",
  "Opening an umbrella indoors and causing a storm",
  "Opera singer breaking glass",
  "Opera singer shattering a crystal disco ball",
  "Origami frog leaping off the table",
  "Origami swan coming to life",
  "Otter playing a tiny xylophone",
  "Owl wearing a smartwatch",
  "Pancake stack doing the limbo",
  "Paper airplane",
  "Paper airplane flying to space",
  "Parachute dive",
  "Parrot giving bad directions",
  "Pencil boxing an eraser",
  "Penguin delivering a pizza",
  "Penguin delivering an important message",
  "Penguin entering a salsa dancing competition",
  "Penguin escaping from a zoo",
  "Penguin slipping on a banana peel",
  "Penguin stealing someone's lunch",
  "Penguin wearing roller skates",
  "Penguins dancing around a campfire",
  "Penguins having a barbecue",
  "Penguins having a picnic on the moon",
  "Penguins playing cards",
  "Penguins riding bicycles",
  "Penguins stealing a picnic",
  "Penguins swimming in a pool",
  "Penguins taking a submarine underwater",
  "Phoenix wing",
  "Phone running away from charger",
  "Pickle jar locked with a padlock",
  "Piece of cake eating a smaller piece of cake",
  "Pigeon fashion model",
  "Pigeon wearing a tiny hat",
  "Pillow with no cool side anywhere",
  "Pirate accidentally walking into a wedding",
  "Pirate arguing over a map",
  "Pirate chasing a chicken",
  "Pirate climbing a lighthouse",
  "Pirate climbing out of a barrel",
  "Pirate digging a hole on the beach",
  "Pirate digging a treasure hole",
  "Pirate digging beneath a palm tree",
  "Pirate discovering a cave",
  "Pirate discovering a treasure beneath the kitchen floor",
  "Pirate finding a secret message",
  "Pirate finding a treasure map in a sandwich",
  "Pirate finding gold coins",
  "Pirate getting seasick on dry land",
  "Pirate getting stuck in a treasure chest",
  "Pirate getting tangled in a rope",
  "Pirate looking for a hidden key",
  "Pirate looking through a telescope",
  "Pirate opening a bottle with a message inside",
  "Pirate parrot squawking state secrets",
  "Pirate sailing toward a mysterious island",
  "Pirate sailing under a rainbow",
  "Pirate searching a haunted island",
  "Pirate searching for a missing treasure",
  "Pirate searching through an old map",
  "Pirate ship",
  "Pirate trying to repair a broken ship",
  "Pirates having a tea party",
  "Pizza delivering a human",
  "Pizza party",
  "Pizza slice surfing a river of tomato sauce",
  "Platypus interviewing for CEO of a bank",
  "Platypus solving an ancient crossword puzzle",
  "Playing a trumpet while riding a camel",
  "Playing baseball with a pumpkin",
  "Playing cards with three aliens",
  "Playing drums in a library",
  "Playing golf on top of a volcano",
  "Playing hide-and-seek with a ghost",
  "Playing ping-pong with an alien",
  "Playing tennis with a watermelon",
  "Pogo stick",
  "Pogo stick marathon on the moon",
  "Polar bear in swim trunks",
  "Popcorn kernel wearing a miniature party hat",
  "Popcorn rain",
  "Porcupine getting stuck in a balloon factory",
  "Possessed alarm clock screaming wake up",
  "Power outlet with an electric mustache",
  "Pretzel twisted into a knot of confusion",
  "Princess climbing out of a castle window",
  "Princess fighting a giant mosquito",
  "Princess rescuing a dragon",
  "Pufferfish inflating inside an elevator",
  "Pug eating a whole pizza",
  "Pushing a door that clearly says pull",
  "QR code leading to a drawing of a duck",
  "Quarterback throwing a flying pizza",
  "Raccoon playing poker with stray cats",
  "Raccoon washing cotton candy",
  "Racing a rocket against a bicycle",
  "Racing a turtle through the city",
  "Rainbow bridge",
  "Rainbow ending inside a bowl of cereal",
  "Rhino delicately threading a needle",
  "Riding a bicycle through space",
  "Riding a horse backwards",
  "Riding a roller coaster through the clouds",
  "Riding a unicycle while holding an umbrella",
  "Robot allergic to electricity",
  "Robot butler",
  "Robot chasing a runaway robot vacuum",
  "Robot cleaning a beach",
  "Robot crying oil tears",
  "Robot dog",
  "Robot exploring an abandoned city",
  "Robot fixing a broken toaster",
  "Robot fixing a car",
  "Robot getting caught in a fishing net",
  "Robot getting stuck in the mud",
  "Robot getting trapped inside a cardboard box",
  "Robot learning to play guitar",
  "Robot making a snow angel",
  "Robot planting a vegetable garden",
  "Robot planting flowers",
  "Robot repairing a bicycle",
  "Robot trying to repair a submarine",
  "Robot trying to untangle Christmas lights",
  "Robot vacuuming a haunted mansion",
  "Robot walking through a desert",
  "Rock having a rock concert for pebbles",
  "Rocket boots",
  "Rockstar smashing a ukulele",
  "Roller coaster",
  "Rollerblading cow",
  "Roomba plotting an escape through the doggy door",
  "Rubber duck general",
  "Running a marathon in high heels",
  "Running away from a rolling snowball",
  "Running away from a swarm of butterflies",
  "Sad robot",
  "Sand castle",
  "Saturn rings",
  "Sea turtle wearing colorful arm floaties",
  "Seagull stealing pizza",
  "Seahorse winning a miniature marathon",
  "Segway tour",
  "Selfie stick taking a photo of nothing",
  "Shark afraid of water",
  "Shark hiding in a bathtub",
  "Sheep with an afro haircut",
  "Shipwreck gold",
  "Shoelaces tied into forty impossible knots",
  "Shooting star",
  "Shopping cart with one wildly spinning wheel",
  "Singing potato",
  "Singing the wrong lyrics with absolute confidence",
  "Siren singing karaoke at a beach tavern",
  "Skeleton in a bubble bath",
  "Skeleton rib xylophone",
  "Skier sliding down a sand dune",
  "Skunk working at a perfume counter",
  "Sleeping through an earthquake",
  "Sleepy dinosaur",
  "Sloth on a sugar rush",
  "Sloth zooming down a zip line",
  "Smart fridge locking out hungry owner",
  "Smart phone",
  "Smart watch",
  "Smart watch checking the pulse of a rock",
  "Snail with a jetpack",
  "Snowman wearing a scarf in summer",
  "Solar panel sunbathing in sunglasses",
  "Sombrero blowing away in a tornado",
  "Someone accidentally launching a watermelon into space",
  "Someone accidentally shrinking a giant",
  "Someone attempting to cook with a hairdryer",
  "Someone balancing on a stack of pancakes",
  "Someone carrying a sleeping elephant",
  "Someone chasing a giant rolling orange",
  "Someone chasing their hat through a windy city",
  "Someone climbing through a giant keyhole",
  "Someone cooking breakfast at midnight",
  "Someone discovering a door in the middle of the ocean",
  "Someone discovering a floating castle",
  "Someone discovering a giant footprint in the snow",
  "Someone discovering a secret underground city",
  "Someone discovering invisible stairs",
  "Someone discovering that their bed is floating",
  "Someone falling asleep during a treasure hunt",
  "Someone falling into a giant bowl of soup",
  "Someone falling through a trapdoor",
  "Someone finding a dinosaur in their backyard",
  "Someone finding a giant key",
  "Someone finding a hidden treasure under the floor",
  "Someone getting stuck in a giant sweater",
  "Someone hiding from a very large duck",
  "Someone juggling while riding a bicycle",
  "Someone opening a door into outer space",
  "Someone opening a gift and finding another gift inside",
  "Someone opening a portal in the kitchen",
  "Someone opening a suitcase full of balloons",
  "Someone opening an umbrella indoors",
  "Someone teaching a dog to play piano",
  "Someone trying to catch a runaway suitcase",
  "Someone trying to fit a sofa into a tiny elevator",
  "Someone wearing twelve pairs of socks",
  "Space cat",
  "Spaghetti noodle tying a bow tie",
  "Sphinx riddle",
  "Spoon acting as a catapult for peas",
  "Spy disguised as a plant",
  "Squirrel burying a shiny gold wristwatch",
  "Squirrel with a treasure chest",
  "Statue of Liberty dropping the torch",
  "Stealing thunder with a net",
  "Stepping into a puddle deeper than expected",
  "Stepping on a squeaky toy during a stealth mission",
  "Stethoscope listening to a watermelon",
  "Struggling to find the start of the tape roll",
  "Suit of armor squeaking loudly with every step",
  "Suitcase bursting open at the airport",
  "Sun applying sunscreen before shining",
  "Superhero hamster",
  "Supersonic speed turtle",
  "Surfer riding a wave of strawberry jam",
  "Surfing penguin",
  "Sushi boat",
  "Sushi roll wearing a seaweed belt",
  "T-Rex struggling to put on a backpack",
  "T-Rex wearing a backpack",
  "Taco exploding on the first bite",
  "Taco taking a siesta",
  "Taco truck",
  "Tailor sewing pants for a giraffe",
  "Taking a dinosaur for a walk",
  "Taking a submarine to the supermarket",
  "Talking tree",
  "Teaching a dinosaur how to use a smartphone",
  "Teaching a fish how to dance",
  "Telescope spying on a cheese moon",
  "The moon fighting the sun over a sandwich",
  "The worst superhero ever",
  "Thermostat having a heat wave panic",
  "Thirsty potted plant",
  "Thunder cloud",
  "Tightrope walker crossing between two skyscrapers",
  "Time running out on a digital sundial",
  "Time traveler paying with crypto",
  "Tiny elephant",
  "Toaster launching bread into orbit",
  "Toilet paper escaping a cat",
  "Tooth fairy getting caught",
  "Toucan balancing a spinning basketball",
  "Traffic cone directing confused pigeons",
  "Traffic cop directing ducks",
  "Traffic light glowing purple in protest",
  "Trampoline jump",
  "Treasure chest",
  "Tree shedding leaves shaped like dollar bills",
  "Tripping over completely flat ground",
  "Trying to balance a tower of books",
  "Trying to carry a giant watermelon",
  "Trying to carry eight grocery bags in one trip",
  "Trying to carry too many groceries",
  "Trying to catch a falling star",
  "Trying to catch a fish with a net full of holes",
  "Trying to eat tacos neatly in a white suit",
  "Trying to escape from a giant spider",
  "Trying to fit a giraffe into a car",
  "Trying to open a jar that is too tight",
  "Trying to open a plastic produce bag with dry fingers",
  "Trying to parallel park an oversized monster truck",
  "Trying to photograph a very shy squirrel",
  "Trying to push a broken-down spaceship",
  "Trying to repair a spaceship with tape",
  "Trying to sneak past a sleeping giant",
  "Trying to sneeze silently in a quiet meeting",
  "Trying to teach a robot sarcasm",
  "Trying to untangle holiday lights in July",
  "Typewriter typing its own mystery novel",
  "UFO abducting a cow",
  "Umbrella blown inside out by a sneeze",
  "Underwater bicycle",
  "Unicorn horn",
  "Unicorn stuck at a toll booth",
  "Unicorn with a traffic cone horn",
  "Unicycle balance",
  "Vampire bat",
  "Vampire putting on sunscreen",
  "Vegan vampire",
  "Vending machine spitting out loose change angrily",
  "Video game controller",
  "Virtual reality",
  "Volcanic eruption",
  "Waiter dropping soup",
  "Walking into a spiderweb and doing karate",
  "Walrus in a tutu",
  "Walrus playing the accordion",
  "Walrus relaxing on an inflatable flamingo",
  "Walrus shaving with whipped cream",
  "Washing machine eating socks",
  "Water slide",
  "Watermelon crying seeds",
  "Watermelon doing a cannonball into a pool",
  "Watermelon rolling down bowling alley lanes",
  "Waving back at someone who was waving to someone else",
  "Wearing two different shoes to a fancy gala",
  "Werewolf brushing fur",
  "Werewolf brushing hair before a date",
  "Werewolf hairdresser",
  "Whale in a top hat",
  "When the wifi goes down",
  "Whispering so quietly nobody can hear",
  "Wi-Fi router smoking from too many cat videos",
  "Wind blowing a toupee onto a statue",
  "Window washer playing tic-tac-toe with an alien",
  "Wizard accidentally creating a second sun",
  "Wizard accidentally turning a castle into a sandwich",
  "Wizard casting a spell",
  "Wizard chasing a magical book",
  "Wizard climbing a ladder into the clouds",
  "Wizard cooking breakfast",
  "Wizard failing a driving test",
  "Wizard flying above a forest",
  "Wizard flying through a city",
  "Wizard forgetting the magic words",
  "Wizard losing a wand in a swimming pool",
  "Wizard playing golf with a broom",
  "Wizard repairing a broken wand",
  "Wizard riding a broomstick",
  "Wizard riding a giant eagle",
  "Wizard searching an enchanted forest",
  "Wizard searching for a dragon",
  "Wizard teaching a broom how to fly",
  "Wizard trying to find a lost wand",
  "Wizard trying to repair a magic mirror",
  "Wizard turned into a potato",
  "Wizard turning a pumpkin into a carriage",
  "Worm in a tiny fedora",
  "Yeti eating strawberry ice cream",
  "Yeti sneeze",
  "Yo-yo hypnotizing a crowd of pigeons",
  "Zebra washing off its stripes at the car wash",
  "Zombie getting a manicure",
  "Zombie hand",
  "Zombie using wrinkle cream"
];

export function pickPrompts(count: number, usedPrompts?: Set<string>): string[] {
  let pool = [...PROMPTS];
  if (usedPrompts) {
    pool = pool.filter(p => !usedPrompts.has(p));
  }

  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }

  while (pool.length < count) pool.push(...PROMPTS);

  const picked = pool.slice(0, count);
  if (usedPrompts) {
    for (const p of picked) usedPrompts.add(p);
  }
  return picked;
}

const REPLACEMENTS: Record<string, string[]> = {
  // Animals
  cat: ["kitten", "raccoon", "tiger", "panther", "fox"],
  dog: ["pug", "corgi", "golden retriever", "wolf", "poodle"],
  dinosaur: ["T-Rex", "dragon", "lizard", "velociraptor"],
  dragon: ["dinosaur", "giant lizard", "gargoyle"],
  bear: ["polar bear", "panda", "grizzly bear"],
  shark: ["dolphin", "whale", "swordfish", "megalodon"],
  penguin: ["duck", "flamingo", "seagull", "pigeon"],
  squirrel: ["hamster", "chipmunk", "raccoon", "mouse"],
  snail: ["slug", "turtle", "sloth", "caterpillar"],
  turtle: ["tortoise", "snail", "sloth"],
  octopus: ["squid", "jellyfish", "crab", "lobster"],
  rabbit: ["bunny", "hare", "hamster"],
  monkey: ["chimpanzee", "gorilla", "baboon"],
  cow: ["bull", "goat", "sheep", "llama"],
  horse: ["unicorn", "donkey", "zebra"],

  // Foods
  pizza: ["giant pancake", "lasagna", "cheeseburger", "flatbread"],
  spaghetti: ["ramen noodles", "pasta", "macaroni"],
  burger: ["cheeseburger", "sandwich", "taco", "burrito"],
  sandwich: ["panini", "sub roll", "burger", "burrito"],
  coffee: ["hot cocoa", "boba tea", "espresso", "latte", "energy drink"],
  tea: ["coffee", "smoothie", "boba", "lemonade"],
  cake: ["birthday cake", "pie", "donut", "giant cupcake"],
  donut: ["bagel", "cookie", "cupcake"],
  cookie: ["biscuit", "brownie", "muffin", "waffle"],
  banana: ["pineapple", "cucumber", "plantain"],
  potato: ["avocado", "tomato", "sweet potato"],
  taco: ["burrito", "quesadilla", "nachos"],

  // Entities & Roles
  robot: ["cyborg", "smart toaster", "mechanical man", "computer"],
  alien: ["extraterrestrial", "astronaut", "monster", "martian"],
  ghost: ["spooky phantom", "vampire", "poltergeist", "sheet monster"],
  vampire: ["Dracula", "bat person", "werewolf", "zombie"],
  zombie: ["mummy", "skeleton", "ghoul"],
  pirate: ["sea captain", "sailor", "buccaneer"],
  wizard: ["sorcerer", "magician", "warlock", "witch"],
  superhero: ["vigilante", "masked hero", "crime fighter"],
  detective: ["private eye", "police officer", "spy"],
  clown: ["jester", "mime", "performer"],

  // Actions
  "riding a bicycle": ["riding a skateboard", "driving a scooter", "on rollerblades", "riding a unicycle"],
  "baking cookies": ["cooking pancakes", "baking a cake", "grilling burgers"],
  "taking a selfie": ["live streaming", "taking a portrait", "recording a video"],
  "stuck in traffic": ["waiting in a long line", "stuck in an elevator", "trapped at a red light"],
  "doing yoga": ["doing karate", "doing ballet", "stretching awkwardly", "doing gymnastics"],
  "doing ballet": ["tap dancing", "doing karate", "breakdancing"],
  "playing the drums": ["playing guitar", "playing trumpet", "playing DJ turntables"],
  "eating spaghetti": ["eating messy noodles", "slurping ramen", "eating soup"],
  "wearing sunglasses": ["wearing 3D glasses", "wearing a monocle", "wearing swim goggles"],
  "planning a heist": ["stealing snacks", "sneaking around", "plotting revenge"]
};

export function generateSmartDecoyPrompt(realPrompt: string, activePrompts: Set<string>, usedPrompts?: Set<string>): string {
  const normReal = realPrompt.trim().toLowerCase();

  // Strategy 1: Find a distinct prompt from PROMPTS that shares a thematic subject/vibe
  const words = normReal
    .replace(/[^\w\s]/g, "")
    .split(/\s+/)
    .filter(w => w.length > 3 && !["with", "this", "that", "from", "into", "over", "under", "about", "your", "their", "trying", "getting"].includes(w));

  const thematicCandidates = PROMPTS.filter(p => {
    const np = p.toLowerCase();
    if (np === normReal || activePrompts.has(p)) return false;
    return words.some(w => np.includes(w));
  });

  if (thematicCandidates.length > 0) {
    return thematicCandidates[Math.floor(Math.random() * thematicCandidates.length)]!;
  }

  // Strategy 2: Pick an unused prompt from the pool
  const pool = pickPrompts(30, usedPrompts).filter(p => p.toLowerCase() !== normReal && !activePrompts.has(p));
  if (pool.length > 0) {
    return pool[0]!;
  }

  const fallback = pickPrompts(50).filter(p => p.toLowerCase() !== normReal && !activePrompts.has(p));
  return fallback[0] || "A mysterious masterpiece";
}



